version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=habits
      - POSTGRES_USER=habits
      - POSTGRES_PASSWORD=habits
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 project.asgi:application"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    ports:
      - "8000:8000"
  worker:
    build: .
    command: celery -A project worker -l info
    depends_on:
      - redis
